# Generated by Django 5.1.5 on 2025-02-03 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URL_Shortner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('1', 'Mobile'), ('2', 'Desktop')], max_length=5)),
                ('click_count', models.IntegerField(default=1)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='URL_Shortner.longtoshort')),
            ],
            options={
                'unique_together': {('short_url', 'country', 'device_type')},
            },
        ),
    ]
