# Generated by Django 5.1.5 on 2025-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URL_Shortner', '0002_clickanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('short_url', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('desktop_clicks', models.PositiveIntegerField(default=0)),
                ('mobile_clicks', models.PositiveIntegerField(default=0)),
                ('country_clicks', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='ClickAnalytics',
        ),
    ]
