# Generated by Django 5.1.5 on 2025-02-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='text',
            field=models.TextField(max_length=250),
        ),
    ]
